# Generated by Django 4.1.5 on 2023-03-25 11:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_ID', models.IntegerField()),
                ('resource_asset_number', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('purpose', models.TextField()),
                ('employee_ID', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('sign_out_date', models.DateField(default=datetime.date.today)),
                ('return_date', models.DateField(default=datetime.date.today)),
                ('returned', models.BooleanField(default=False)),
                ('returned_on', models.DateField(null=True)),
            ],
            options={
                'verbose_name': 'Resource Sign-out Log',
                'verbose_name_plural': 'Resource Sign-out Logs',
            },
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.FileField(upload_to='uploads/signature_archive')),
                ('log_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loaning.log')),
            ],
            options={
                'verbose_name': 'Resource Sign-out Sheet',
                'verbose_name_plural': 'Resource Sign-out Sheets',
            },
        ),
    ]
