# Generated by Django 4.1.5 on 2023-02-11 20:37

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0004_supplier_category_alter_asset_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.TextField()),
                ('purpose', models.TextField()),
                ('ID_number', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d+$', 'ID number must be 8 numeric values.'), django.core.validators.MinLengthValidator(8, 'ID number must be 8 numeric values.')])),
                ('borrow_date', models.DateField(default=datetime.date.today)),
                ('return_date', models.DateField(default=datetime.date.today)),
                ('resource_asset_number', models.ForeignKey(limit_choices_to={'available_to_borrow': True}, on_delete=django.db.models.deletion.CASCADE, to='management.asset')),
            ],
            options={
                'verbose_name': 'Loan History',
                'verbose_name_plural': 'Loan History',
            },
        ),
        migrations.CreateModel(
            name='Current',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.TextField()),
                ('purpose', models.TextField()),
                ('ID_number', models.CharField(max_length=8)),
                ('borrow_date', models.DateField(default=datetime.date.today)),
                ('resource_asset_number', models.ForeignKey(limit_choices_to={'available_to_borrow': True}, on_delete=django.db.models.deletion.CASCADE, to='management.asset')),
            ],
            options={
                'verbose_name': 'Currently Loaned Asset',
                'verbose_name_plural': 'Currently Loaned Assets',
            },
        ),
    ]
