# Generated by Django 4.1.5 on 2023-02-10 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loaning', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='current',
            options={'verbose_name': 'Currently Loaned Asset', 'verbose_name_plural': 'Currently Loaned Assets'},
        ),
        migrations.AlterModelOptions(
            name='log',
            options={'verbose_name': 'Loan History', 'verbose_name_plural': 'Loan History'},
        ),
    ]
