# Generated by Django 4.1.7 on 2023-03-31 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loaning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='returned_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
