# Generated by Django 4.1.5 on 2023-02-10 19:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loaning', '0002_alter_current_options_alter_log_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='ID_number',
            field=models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(8, 'ID number must be 8 numeric values.'), django.core.validators.RegexValidator('^[0-9+]', 'ID number must be 8 numeric values.')]),
        ),
    ]
