# Generated by Django 4.1.7 on 2023-03-31 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loaning', '0002_alter_log_returned_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signature',
            options={'permissions': (('view_signature', 'Can view signature'),), 'verbose_name': 'Resource Sign-out Sheet', 'verbose_name_plural': 'Resource Sign-out Sheets'},
        ),
    ]
