# Generated by Django 4.1.7 on 2023-03-31 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loaning', '0003_alter_signature_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.FileField(upload_to='uploads/signature_archive')),
                ('log_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loaning.log')),
            ],
            options={
                'verbose_name': 'Resource Sign-out Sheet',
                'verbose_name_plural': 'Resource Sign-out Sheets',
            },
        ),
    ]
