# Generated by Django 4.1.5 on 2023-02-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loaning', '0004_alter_log_signatures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='signatures',
            field=models.ImageField(blank=True, default='1', upload_to='uploads/signature_archive'),
        ),
    ]
