# Generated by Django 4.1.5 on 2023-02-19 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loaning', '0005_alter_log_signatures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='signatures',
        ),
        migrations.AddField(
            model_name='current',
            name='return_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='log',
            name='ID_number',
            field=models.CharField(max_length=8),
        ),
    ]
