# Generated by Django 4.1.7 on 2023-04-01 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loaning', '0005_delete_sig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signature',
            options={'verbose_name': 'Resource Sign-out Sheet', 'verbose_name_plural': 'Resource Sign-out Sheets'},
        ),
    ]
