# Generated by Django 4.1.5 on 2023-02-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_supplier_unique_together'),
        ('loaning', '0006_remove_log_signatures_current_return_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Current',
            new_name='Logg',
        ),
        migrations.AlterModelOptions(
            name='log',
            options={'verbose_name': 'Currently Loaned Asset', 'verbose_name_plural': 'Currently Loaned Assets'},
        ),
        migrations.AlterModelOptions(
            name='logg',
            options={'verbose_name': 'Loan History', 'verbose_name_plural': 'Loan History'},
        ),
        migrations.AddField(
            model_name='log',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
