# Generated by Django 4.1.5 on 2023-02-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loaning', '0007_rename_current_logg_alter_log_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.ImageField(upload_to='')),
            ],
        ),
    ]
