# Generated by Django 4.1.5 on 2023-02-26 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loaning', '0008_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='signature',
            field=models.FileField(upload_to=''),
        ),
    ]
