# Generated by Django 4.1.5 on 2023-02-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loaning', '0009_alter_signature_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='signature',
            field=models.FileField(upload_to='uploads/signature_archive'),
        ),
    ]
