# Generated by Django 4.1.5 on 2023-03-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loaning', '0010_alter_signature_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='returned_on',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='Logg',
        ),
    ]
