# Generated by Django 4.1.5 on 2023-03-05 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_remove_device_category_remove_device_supplier_and_more'),
        ('loaning', '0011_log_returned_on_delete_logg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='item_description',
            new_name='model',
        ),
        migrations.AddField(
            model_name='log',
            name='asset_ID',
            field=models.ForeignKey(default='', limit_choices_to={'available_to_borrow': True}, on_delete=django.db.models.deletion.CASCADE, to='management.asset'),
        ),
        migrations.AlterField(
            model_name='log',
            name='resource_asset_number',
            field=models.TextField(),
        ),
    ]
