# Generated by Django 4.1.5 on 2023-03-05 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_remove_device_category_remove_device_supplier_and_more'),
        ('loaning', '0012_rename_item_description_log_model_log_asset_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='asset_ID',
            field=models.ForeignKey(limit_choices_to={'available_to_borrow': True}, on_delete=django.db.models.deletion.CASCADE, to='management.asset'),
        ),
    ]
