# Generated by Django 4.1.5 on 2023-03-05 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loaning', '0013_alter_log_asset_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'verbose_name': 'Resource Sign-out Log', 'verbose_name_plural': 'Resource Sign-out Logs'},
        ),
    ]
