# Generated by Django 4.1.5 on 2023-03-07 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loaning', '0014_alter_log_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='loan_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loaning.log'),
        ),
    ]
