# Generated by Django 4.1.5 on 2023-03-13 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loaning', '0015_signature_loan_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signature',
            old_name='loan_id',
            new_name='log_id',
        ),
    ]
