# Generated by Django 4.1.5 on 2023-02-11 19:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='model', max_length=100)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.category')),
                ('supplier', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_asset_number', models.CharField(max_length=255)),
                ('purchase_date', models.DateField(default=datetime.date.today)),
                ('memory_size', models.CharField(default='64', max_length=10)),
                ('color', models.CharField(choices=[('WHITE', 'White'), ('GRAY', 'Gray'), ('BLACK', 'Black'), ('RED', 'Red'), ('PINK', 'Pink'), ('BLUE', 'Blue'), ('GREEN', 'Green'), ('YELLOW', 'Yellow'), ('ORANGE', 'Orange'), ('PURPLE', 'Purple')], default='BLACK', max_length=10)),
                ('description', models.TextField(help_text='Add extra information', null=True)),
                ('supplier', models.CharField(max_length=255)),
                ('production_date', models.DateField(default=datetime.date.today)),
                ('bill_number', models.CharField(max_length=255)),
                ('bill_image', models.ImageField(upload_to='uploads/bill_archive')),
                ('available_to_borrow', models.BooleanField(default=True)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.category')),
                ('model', models.ForeignKey(default=1, limit_choices_to={'category': models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.category'), 'supplier': models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.supplier')}, on_delete=django.db.models.deletion.CASCADE, to='management.device')),
            ],
            options={
                'verbose_name': 'CCIT Asset',
                'verbose_name_plural': 'CCIT Asset',
            },
        ),
    ]
