# Generated by Django 4.1.5 on 2023-01-25 09:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(default=datetime.date.today)),
                ('supplier', models.CharField(max_length=100)),
                ('production_date', models.DateField(default=datetime.date.today)),
                ('bill_number', models.CharField(max_length=200)),
                ('bill_image', models.ImageField(upload_to='uploads/bill_archive')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.category')),
            ],
        ),
    ]
