# Generated by Django 4.1.5 on 2023-01-25 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_brand_model_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.brand'),
        ),
        migrations.AddField(
            model_name='device',
            name='model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.model'),
        ),
    ]
