# Generated by Django 4.1.5 on 2023-02-11 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_asset_model_alter_device_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='model',
            field=models.ForeignKey(default=1, limit_choices_to={'category': models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.category'), 'supplier': models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.supplier')}, on_delete=django.db.models.deletion.CASCADE, to='management.device'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.supplier'),
        ),
    ]
