# Generated by Django 4.1.5 on 2023-02-11 19:36

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_asset_model_alter_asset_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.category'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='model',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='supplier', chained_model_field='supplier', on_delete=django.db.models.deletion.CASCADE, to='management.device'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='supplier',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='category', chained_model_field='category', on_delete=django.db.models.deletion.CASCADE, to='management.supplier'),
        ),
        migrations.AlterField(
            model_name='device',
            name='supplier',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='category', chained_model_field='category', on_delete=django.db.models.deletion.CASCADE, to='management.supplier'),
        ),
    ]
