# Generated by Django 4.1.5 on 2023-02-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_supplier_category_alter_asset_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='memory_size',
            field=models.CharField(choices=[('2', '2GB'), ('4', '4GB'), ('8', '8GB'), ('12', '12GB'), ('16', '16GB'), ('18', '18GB'), ('24', '24GB'), ('32', '32GB'), ('64', '64GB'), ('48', '48GB'), ('128', '128GB'), ('256', '256GB')], default='64', max_length=10),
        ),
    ]
