# Generated by Django 4.1.5 on 2023-01-25 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alter_device_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='bill_number',
        ),
        migrations.RemoveField(
            model_name='device',
            name='supplier',
        ),
    ]
