# Generated by Django 4.1.5 on 2023-02-13 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alter_asset_memory_size'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together={('supplier', 'category')},
        ),
    ]
