# Generated by Django 4.1.5 on 2023-02-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_supplier_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='category',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='color',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='memory_size',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='model',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='supplier',
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_enrolled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_id',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_os',
            field=models.CharField(default='', max_length=100),
        ),
    ]
