# Generated by Django 4.1.5 on 2023-01-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_device_bill_number_device_resource_asset_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='color',
            field=models.CharField(choices=[('PI', 'Chiffon Pink'), ('BL', 'Angora Blue')], default='PI', max_length=2),
        ),
        migrations.AddField(
            model_name='model',
            name='description',
            field=models.TextField(default='Enter description...'),
        ),
        migrations.AddField(
            model_name='model',
            name='memory',
            field=models.CharField(default='64GB', max_length=200),
        ),
        migrations.AlterField(
            model_name='model',
            name='name',
            field=models.CharField(default='Name...', max_length=100),
        ),
    ]
