# Generated by Django 4.1.5 on 2023-02-28 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_remove_asset_category_remove_asset_color_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='asset_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='asset_enrolled',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='asset_os',
        ),
        migrations.AddField(
            model_name='asset',
            name='enrollment_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='asset',
            name='last_contact',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='asset',
            name='model',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='asset',
            name='os_version',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(default='', max_length=255),
        ),
    ]
