# Generated by Django 4.1.5 on 2023-01-26 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_model_color_model_description_model_memory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='color',
            field=models.CharField(choices=[('PI', 'Pink'), ('BL', 'Blue')], default='PI', max_length=2),
        ),
    ]
