# Generated by Django 4.1.5 on 2023-01-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_alter_model_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='color',
        ),
        migrations.RemoveField(
            model_name='model',
            name='description',
        ),
        migrations.RemoveField(
            model_name='model',
            name='memory',
        ),
        migrations.AddField(
            model_name='device',
            name='color',
            field=models.CharField(choices=[('PI', 'Pink'), ('BL', 'Blue')], default='PI', max_length=2),
        ),
        migrations.AddField(
            model_name='device',
            name='memory',
            field=models.CharField(default='64GB', max_length=200),
        ),
        migrations.AlterField(
            model_name='model',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
