# Generated by Django 4.1.5 on 2023-02-28 13:53

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_remove_asset_production_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='enrollment_date',
            field=models.DateTimeField(default=django.utils.datetime_safe.date.today),
        ),
        migrations.AlterField(
            model_name='asset',
            name='last_contact',
            field=models.DateTimeField(default=django.utils.datetime_safe.date.today),
        ),
        migrations.AlterField(
            model_name='asset',
            name='purchase_date',
            field=models.DateTimeField(blank=True, default=django.utils.datetime_safe.date.today, null=True),
        ),
    ]
