# Generated by Django 4.1.5 on 2023-02-28 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_alter_asset_enrollment_date_alter_asset_last_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='enrollment_date',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='asset',
            name='last_contact',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='asset',
            name='purchase_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.today, null=True),
        ),
    ]
