# Generated by Django 4.1.5 on 2023-01-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_remove_model_color_remove_model_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='bill_number',
            field=models.IntegerField(default='000', max_length=255),
        ),
    ]
