# Generated by Django 4.1.5 on 2023-02-28 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_alter_asset_enrollment_date_alter_asset_last_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='name',
            new_name='username',
        ),
    ]
