# Generated by Django 4.1.5 on 2023-02-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_rename_name_asset_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='user_email',
            field=models.CharField(default='', max_length=255),
        ),
    ]
