# Generated by Django 4.1.5 on 2023-01-26 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_alter_device_bill_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='color',
        ),
        migrations.RemoveField(
            model_name='device',
            name='memory',
        ),
    ]
