# Generated by Django 4.1.5 on 2023-03-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_asset_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='username',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='os_version',
            new_name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='enrollment_date',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='last_contact',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='serial_number',
        ),
        migrations.AddField(
            model_name='asset',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
