# Generated by Django 4.1.5 on 2023-01-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_remove_device_color_remove_device_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='color',
            field=models.CharField(choices=[('PI', 'Pink'), ('BL', 'Blue')], default='PI', max_length=2),
        ),
        migrations.AddField(
            model_name='device',
            name='memory',
            field=models.CharField(default='64GB', max_length=200),
        ),
    ]
