# Generated by Django 4.1.5 on 2023-03-02 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_rename_username_asset_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'verbose_name': 'CCIT Asset', 'verbose_name_plural': 'CCIT Assets'},
        ),
        migrations.RemoveField(
            model_name='asset',
            name='description',
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='bill_image',
            field=models.ImageField(null=True, upload_to='uploads/bill_archive'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='bill_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='manufacturer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='asset',
            name='model',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='asset',
            name='purchase_date',
            field=models.DateTimeField(default=datetime.datetime.today, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='resource_asset_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='user_email',
            field=models.CharField(max_length=255),
        ),
    ]
