# Generated by Django 4.1.5 on 2023-01-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_alter_device_bill_number_alter_device_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='description',
            field=models.TextField(help_text='Add a description', null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='supplier',
            field=models.CharField(help_text='Enter supplier name', max_length=255),
        ),
    ]
