# Generated by Django 4.1.5 on 2023-01-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_alter_device_description_alter_device_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='description',
            field=models.TextField(help_text='Add extra information', null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='supplier',
            field=models.CharField(max_length=255),
        ),
    ]
