# Generated by Django 4.1.5 on 2023-01-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_alter_device_description_alter_device_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='resource_asset_number',
            field=models.CharField(max_length=255),
        ),
    ]
