# Generated by Django 4.1.5 on 2023-01-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_remove_device_brand_remove_device_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='memory',
        ),
        migrations.AddField(
            model_name='device',
            name='memory_size',
            field=models.CharField(default='64', max_length=10),
        ),
    ]
