# Generated by Django 4.1.5 on 2023-01-30 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_remove_device_memory_device_memory_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.brand'),
        ),
        migrations.AddField(
            model_name='device',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.category'),
        ),
    ]
