# Generated by Django 4.1.5 on 2023-01-31 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0025_alter_category_options_alter_category_brand_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='category_brand',
            options={'verbose_name': 'category & brand', 'verbose_name_plural': 'categories & brands'},
        ),
        migrations.AlterField(
            model_name='device',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.category_brand'),
        ),
    ]
