# Generated by Django 4.1.5 on 2023-01-31 15:26

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0028_alter_devicemodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='category',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='brand', chained_model_field='brand', on_delete=django.db.models.deletion.CASCADE, to='management.category_brand'),
        ),
        migrations.AlterField(
            model_name='device',
            name='model',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='category', chained_model_field='category', on_delete=django.db.models.deletion.CASCADE, to='management.devicemodel'),
        ),
    ]
