# Generated by Django 4.1.5 on 2023-02-05 18:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0029_alter_device_category_alter_device_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_asset_number', models.CharField(max_length=255)),
                ('purchase_date', models.DateField(default=datetime.date.today)),
                ('memory_size', models.CharField(default='64', max_length=10)),
                ('color', models.CharField(choices=[('WHITE', 'White'), ('GRAY', 'Gray'), ('BLACK', 'Black'), ('RED', 'Red'), ('PINK', 'Pink'), ('BLUE', 'Blue'), ('GREEN', 'Green'), ('YELLOW', 'Yellow'), ('ORANGE', 'Orange'), ('PURPLE', 'Purple')], default='BLACK', max_length=10)),
                ('description', models.TextField(help_text='Add extra information', null=True)),
                ('production_date', models.DateField(default=datetime.date.today)),
                ('bill_number', models.CharField(max_length=255)),
                ('bill_image', models.ImageField(upload_to='uploads/bill_archive')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(default='1', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='category_brand',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='category_brand',
            name='type',
        ),
        migrations.RemoveField(
            model_name='devicemodel',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='devicemodel',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'model', 'verbose_name_plural': 'models'},
        ),
        migrations.RemoveField(
            model_name='device',
            name='bill_image',
        ),
        migrations.RemoveField(
            model_name='device',
            name='bill_number',
        ),
        migrations.RemoveField(
            model_name='device',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='device',
            name='category',
        ),
        migrations.RemoveField(
            model_name='device',
            name='color',
        ),
        migrations.RemoveField(
            model_name='device',
            name='description',
        ),
        migrations.RemoveField(
            model_name='device',
            name='memory_size',
        ),
        migrations.RemoveField(
            model_name='device',
            name='model',
        ),
        migrations.RemoveField(
            model_name='device',
            name='production_date',
        ),
        migrations.RemoveField(
            model_name='device',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='device',
            name='resource_asset_number',
        ),
        migrations.AddField(
            model_name='device',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Category_Brand',
        ),
        migrations.DeleteModel(
            name='DeviceModel',
        ),
        migrations.AddField(
            model_name='asset',
            name='device',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='supplier', chained_model_field='supplier', on_delete=django.db.models.deletion.CASCADE, to='management.device'),
        ),
        migrations.AddField(
            model_name='asset',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.supplier'),
        ),
        migrations.AlterField(
            model_name='device',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.supplier'),
        ),
    ]
