# Generated by Django 4.1.5 on 2023-02-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0030_asset_supplier_remove_category_brand_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='category',
            field=models.CharField(default='MC', max_length=10),
        ),
    ]
