# Generated by Django 4.1.5 on 2023-02-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0031_alter_supplier_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='memory_size',
            field=models.CharField(choices=[('2', '2GB'), ('4', '4GB'), ('8', '8GB'), ('12', '12GB'), ('16', '16GB'), ('18', '18GB'), ('24', '24GB'), ('32', '32GB'), ('64', '64GB'), ('48', '48GB'), ('128', '128GB'), ('256', '256GB')], default='64', max_length=10),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='category',
            field=models.CharField(choices=[('MC', 'Mobile computer'), ('MP', 'Mobile phone'), ('WC', 'Wearable computer')], default='MC', max_length=10),
        ),
    ]
