# Generated by Django 4.1.5 on 2023-02-05 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0032_alter_asset_memory_size_alter_supplier_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='asset_suppliers', to='management.supplier'),
        ),
    ]
