# Generated by Django 4.1.5 on 2023-02-05 18:42

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0033_alter_asset_supplier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={},
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.CharField(choices=[('MC', 'Mobile computer'), ('MP', 'Mobile phone'), ('WC', 'Wearable computer')], default='MC', max_length=10),
        ),
        migrations.AddField(
            model_name='device',
            name='category',
            field=models.CharField(choices=[('MC', 'Mobile computer'), ('MP', 'Mobile phone'), ('WC', 'Wearable computer')], default='MC', max_length=10),
        ),
        migrations.AlterField(
            model_name='asset',
            name='device',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='category', chained_model_field='category', on_delete=django.db.models.deletion.CASCADE, to='management.device'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.supplier'),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('supplier', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together={('name', 'category')},
        ),
    ]
