# Generated by Django 4.1.5 on 2023-02-05 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0034_alter_device_options_asset_category_device_category_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='device',
            unique_together=set(),
        ),
    ]
