# Generated by Django 4.1.5 on 2023-02-05 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0035_alter_device_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('name', 'supplier', 'category')},
        ),
    ]
