# Generated by Django 4.1.5 on 2023-02-05 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0039_category_rename_name_supplier_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.category'),
        ),
    ]
