# Generated by Django 4.1.5 on 2023-02-05 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0041_alter_supplier_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Supplier',
            new_name='Brand',
        ),
    ]
