# Generated by Django 4.1.5 on 2023-02-05 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0042_rename_supplier_brand'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brand',
            new_name='Supplier',
        ),
    ]
