# Generated by Django 4.1.5 on 2023-02-05 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0043_rename_brand_supplier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
