# Generated by Django 4.1.5 on 2023-02-05 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0044_alter_category_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='category',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.supplier'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('supplier', 'category')},
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='category',
        ),
    ]
