# Generated by Django 4.1.5 on 2023-02-05 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0045_alter_supplier_unique_together_category_supplier_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Asset',
            new_name='CCIT_Asset',
        ),
    ]
