# Generated by Django 4.1.5 on 2023-02-05 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0047_rename_ccit_asset_asset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'verbose_name': 'CCIT Asset', 'verbose_name_plural': 'CCIT Assets'},
        ),
    ]
