# Generated by Django 4.1.5 on 2023-02-05 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0048_alter_asset_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'type of mobile assets', 'verbose_name_plural': 'types of mobile asset'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'supplier model', 'verbose_name_plural': 'supplier models'},
        ),
    ]
