# Generated by Django 4.1.5 on 2023-02-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0050_alter_category_options_alter_device_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
