# Generated by Django 4.1.5 on 2023-02-09 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0051_asset_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='available',
            new_name='available_to_borrow',
        ),
    ]
